services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend_net

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - backend_net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - frontend_net
      - backend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        EXPO_PUBLIC_API_URL: http://localhost:80/api
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/components:/app/components
      - ./frontend/constants:/app/constants
      - ./frontend/context:/app/context
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - frontend_net

volumes:
  postgres_data:

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge