services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - internal

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        EXPO_PUBLIC_API_URL: http://192.168.0.69:80/api
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge