version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:noble
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  