services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:noble
    volumes:
      - ../..:/workspaces:cached
      - frontend-node-modules:/workspaces/${localWorkspaceFolderBasename}/frontend/node_modules
    command: sleep infinity
    ports:
      - "5000:5000"
      - "8081:8081"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  frontend-node-modules: